### ISSUE TITLE
Installation instructions

### ISSUE THREAD

**Issue by Zignature** [yuiji/spotify-web-player-clone#12]
Apart from running `npm install` in the `client` and `server` folders, what needs to be done?

Which `REDIRECT_URI` needs to be set in `server/.env`?

`VITE_` constants in `client/.env`?

**Comment by yalperg** [comment]
First of all, I would like to point out that there are some mistakes that need to be corrected in the project. If I have time in the future, I will update it. However, let me explain how you can run the current version on your local.

Firstly, you need to go to this link "https://developer.spotify.com/dashboard" and create an app. The Redirect URI here should be the URI where your client is running on your local, which, in my case is "http://localhost:5173/". Then click on settings and get your client_id and client_secret keys.

Create a `.env` file in both the server and client folders and fill them in as follows: 

`client/.env`  :

VITE_CLIENT_ID="The client id you get from the spotify app dashboard"
VITE_REDIRECT_URI="The URI where your client is running on your local. It must be the same as the one in the spotify app dashboard"
VITE_SERVER_URI="The URI where your server is running on your local."
VITE_AUTH_URL="https://accounts.spotify.com/authorize?client_id=YOUR_CLIENT_ID&response_type=code&redirect_uri=YOUR_REDIRECT_URI&scope=user-read-private"

`server/.env` :

CLIENT_ID="The client id you get from the spotify app dashboard"
CLIENT_SECRET="The client secret you get from the spotify app dashboard"
REDIRECT_URI="The URI where your client is running on your local. It must be the same as the one in the spotify app dashboard"

**Comment by yalperg** [comment]
Also, if you want to change the scope in the auth uri, this [link](https://developer.spotify.com/documentation/web-api/concepts/scopes) might be helpful.
